# Generated by Django 6.0.1 on 2026-01-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg_username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
